### ISSUE TITLE
make run-server: "ModuleNotFoundError: No module named 'psycopg2'"

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#57]
Environment:  Mac OS

```
python3 -m venv env
source env/bin/activate
pip install -r ./requirements.txt


$ make run-server
python ./kai/server.py
Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/kai/./kai/server.py", line 26, in <module>
    from incident_store_advanced import Application, EmbeddingInstructor, PSQLIncidentStore
  File "/Users/jmatthews/git/jwmatthews/kai/kai/incident_store_advanced.py", line 14, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
make: *** [run-server] Error 1
```

**Comment by jwmatthews** [comment]
On MacOS I am seeing:

```

$ pip install pyscopg2
Collecting pyscopg2
  Using cached pyscopg2-66.0.3.tar.gz (1.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyscopg2
  Building wheel for pyscopg2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      /Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'readme'
        warnings.warn(msg)
      running bdist_wheel
      running build
      /Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      installing to build/bdist.macosx-13.0-arm64/wheel
      running install
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/l1/1b7gzz8n02b5nrtdq51bnj4r0000gn/T/pip-install-gdua8mf9/pyscopg2_2ea65443422a4b2ea1564922a2e21a2b/setup.py", line 10, in <module>
          setup(
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 403, in run
          self.run_command("install")
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/l1/1b7gzz8n02b5nrtdq51bnj4r0000gn/T/pip-install-gdua8mf9/pyscopg2_2ea65443422a4b2ea1564922a2e21a2b/setup.py", line 7, in run
          raise RuntimeError("You are trying to install a stub package pyscopg2. Maybe you are using the wrong pypi?")
      RuntimeError: You are trying to install a stub package pyscopg2. Maybe you are using the wrong pypi?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscopg2
  Running setup.py clean for pyscopg2
Failed to build pyscopg2
ERROR: Could not build wheels for pyscopg2, which is required to install pyproject.toml-based projects
```

**Comment by jwmatthews** [comment]
Looks like I just needed to install the binary package
```
$ pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.9-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.4 kB)
Downloading psycopg2_binary-2.9.9-cp312-cp312-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 2.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.9
```


```
 $ make run-server            
python ./kai/server.py
Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/kai/./kai/server.py", line 26, in <module>
    from incident_store_advanced import Application, EmbeddingInstructor, PSQLIncidentStore
  File "/Users/jmatthews/git/jwmatthews/kai/kai/incident_store_advanced.py", line 17, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
make: *** [run-server] Error 1

```


```
$ pip3 install torch torchvision

$ make run-server               
python ./kai/server.py
Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/kai/./kai/server.py", line 26, in <module>
    from incident_store_advanced import Application, EmbeddingInstructor, PSQLIncidentStore
  File "/Users/jmatthews/git/jwmatthews/kai/kai/incident_store_advanced.py", line 19, in <module>
    from InstructorEmbedding import INSTRUCTOR
ModuleNotFoundError: No module named 'InstructorEmbedding'
make: *** [run-server] Error 1

```


Think the deps are identified, will update requirements.txt next
