### ISSUE TITLE
ModuleNotFoundError: No module named 'InstructorEmbedding'

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#59]
```
 $ make run-server                      
python ./kai/server.py
Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/kai/./kai/server.py", line 26, in <module>
    from incident_store_advanced import Application, EmbeddingInstructor, PSQLIncidentStore
  File "/Users/jmatthews/git/jwmatthews/kai/kai/incident_store_advanced.py", line 19, in <module>
    from InstructorEmbedding import INSTRUCTOR
ModuleNotFoundError: No module named 'InstructorEmbedding'
make: *** [run-server] Error 1

```

**Comment by savitharaghunathan** [comment]
closing this as this PR is merged now -  https://github.com/konveyor-ecosystem/kai/pull/62
