### ISSUE TITLE
Difficult to debug a 422 from server

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#88]
I passed in a malformed body to the API (was missing a required field, 'incident_snip').

It was a little hard for me to understand what was causing the 422.

What I saw was:
- The response returned a status code of 422
- When I looked at the output from `make run-server` I saw:  `post_get_incident_solution recv'd: <Request POST /get_incident_solution >`

It would be nice if we could log another message about what was missing in the request to help future debugging, or maybe we are logging this and I just don't know where to look.

**Comment by jwmatthews** [comment]
I tried to recreate this and I'm seeing a 500 and can debug better as I see the below from `make run-server` logs

```
Error handling request
Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/env/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/./kai/server.py", line 308, in post_get_incident_solution
    llm_output = get_incident_solution(await request.json(), False).content
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmatthews/git/jwmatthews/kai/./kai/server.py", line 214, in get_incident_solution
    incident_snip: str = request_json["incident_snip"]
                         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'incident_snip'
```

Based on this, think we can close this issue
